name = "live-app"
compatibility_date = "2025-05-08"
main = ".vercel/output/static/_worker.js/index.js"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[site]
bucket = ".vercel/output/static"

