name = "live-app"
compatibility_date = "2025-05-08"
compatibility_flags = ["nodejs_compat"]

# page mode
pages_build_output_dir = ".vercel/output/static"

# worker mode
# main = ".vercel/output/static/_worker.js/index.js"
# site = { bucket = "./.vercel/output/static" }


